// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DemoStarter.Migrations
{
    [DbContext(typeof(CoffeeShopContext))]
    [Migration("20191008193729_sqlserverinit")]
    partial class sqlserverinit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CloseTime");

                    b.Property<string>("OpenTime");

                    b.Property<string>("StreetAddress");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");

                    b.HasData(
                        new { LocationId = 999, CloseTime = "4PM", OpenTime = "6AM", StreetAddress = "999 Main Street" }
                    );
                });

            modelBuilder.Entity("Unit", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Acquired");

                    b.Property<int>("BrewerTypeId");

                    b.Property<int?>("LocationId");

                    b.HasKey("UnitId");

                    b.HasIndex("LocationId");

                    b.ToTable("Unit");
                });

            modelBuilder.Entity("Unit", b =>
                {
                    b.HasOne("Location")
                        .WithMany("BrewingUnits")
                        .HasForeignKey("LocationId");
                });
#pragma warning restore 612, 618
        }
    }
}
